### ISSUE TITLE
Import repo from organization?

### ISSUE THREAD

**Issue by Lamby777** [nektro/aquila#19]
Don't know if this is already a thing, so sorry if this is a certified skill issue, but I couldn't find any packages uploaded by GitHub organization accounts on [aquila.red](https://aquila.red/). The "Import" tab only shows stuff I have on this account and not any from orgs despite granting permissions for everything in the OAuth2 step.

**Comment by nektro** [comment]
Hi! This was not factored into the original design as I wanted to promote packages from users. Unfortunately this repo has fallen out of maintenance due to the velocity of Zig and me moving onto other projects in the short term. The landscape of Zig web development has completely changed in the time since this project's latest commit but it does still contain some pretty good patterns so that's why I keep it open.

Additionally there are a number of other features for this that I decided I wanted to pause and I've been working on a new project that's a selfhosted git server.

**Comment by Lamby777** [comment]
Forgot to close this, closing now
